---
kind: pipeline
type: docker
name: Deploy To Server

steps:
- name: upload
  image: cschlosser/drone-ftps
  environment:
    FTP_USERNAME:
      from_secret: ftp_username
    FTP_PASSWORD:
      from_secret: ftp_password
    PLUGIN_HOSTNAME: 
      from_secret: hostname

    PLUGIN_EXCLUDE: ^\.git/$
  when:
    branch:
    - master
    event:
    - push    