version: '3.5'

services:
  web:
    build:
      context: .
      target: builder
    environment:
      APP_PORT: "8080"
    command: make build run
    volumes:
      - .:/app
    ports:
      - 8080:8080
