name: Continuous Integration

on:
  push:
    tags:
      - "*"  

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and push image to Dockerhub
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: geraldoandrade/geraldoandrade.com
        tag_with_ref: true          
