name: Continuous Integration

on:
  push:
    tags:
      - "*"  

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and push image to Dockerhub
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: geraldoandradee/geraldoandrade.com
        tag_with_ref: true   
    - name: Get Branch and Tag Name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}               
    - name: Use Deploy Action
      if: success()
      uses: kalmhq/kalm-deploy-action@v0.0.3
      id: deploy
      with:
        KALM_API_ADDRESS: ${{ secrets.KALM_API_ADDRESS }}
        KALM_DEPLOY_KEY: ${{ secrets.KALM_DEPLOY_KEY }}
        KALM_APP: "personal-site"
        KALM_COMPONENT: "site"
        KALM_COMPONENT_IMG_TAG: "${{ steps.branch_name.outputs.SOURCE_TAG }}"
    - name: output of step deploy
      if: success()
      run: echo 'The callback response was ${{ steps.deploy.outputs.resp }}.'